# website info
metadata:
  title: "MyWebsite"
  author: "Seth"
  link: "https://sethdeltarune101.github.io"
  in_development: true
  release_date: 01.09.2026 
  # dd.mm.yyyy
  mime_types:
    mime_type_1: "text/html"
    mime_type_2: "text/javascript"
    mime_type_3: "text/css"
    mime_type_4: "application/yaml"
